spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3310/product?createDatabaseIfNotExist=true
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: mariadb

